version: 2
jobs:
  build:
    docker:
      - image: circleci/mysql:5.7
        environment:
          - PLATFORM: "2.0"
          - S3_BUCKET: "s3://ci-bench2"

      - image: circleci/mysql:5.7

    working_directory: /tmp/code
    steps:
      - run: curl -s https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh | bash
      - run: apt -y install curl jq awscli git sysbench

      - checkout

      - run: git clean -f .; git checkout master

      - run: ./benchmark.sh $PLATFORM $S3_BUCKET
